#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu
#SBATCH -p res-gpu-large
#SBATCH --qos=short
#SBATCH --job-name=OthelloCNN
#SBATCH -o ./Results/CNN8modelGeneration.txt

source /etc/profile
module load cuda/10.1

python3 ./DeepLearning/othelloCNN8.py
