#!/bin/bash
#SBATCH -N 2
#SBATCH -c 16
#SBATCH -p cpu
#SBATCH --qos=short
#SBATCH --job-name=OthelloData
#SBATCH -o ./Data/DataLoadOutput.txt

source /etc/profile
module load cuda/10.1

python3 ./DeepLearning/WThorParser.py
