#!/bin/bash
#SBATCH -N 3
#SBATCH -c 16
#SBATCH -p cpu
#SBATCH --qos=short
#SBATCH --job-name=CValTester
#SBATCH -o ./Results/AgentTesting/CValTestResults.txt

source /etc/profile
module load cuda/10.1

python3 ./CValTest.py
