#!/bin/bash
#SBATCH -N 4
#SBATCH -c 16
#SBATCH -p cpu
#SBATCH --qos=short
#SBATCH --job-name=Othello_VS_Tests
#SBATCH -o ./Results/AgentTesting/WendyVsMC30_Part2

source /etc/profile
module load cuda/10.1

python3 ./mainTest.py -n 125 -pW W -pD M30
