#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu
#SBATCH -p ug-gpu-small
#SBATCH --qos=debug
#SBATCH --job-name=OthelloCNN


source /etc/profile
module load cuda/10.1

python3 ./othelloCNN.py
